name: tests

on: push

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # cache the dependencies from any node_modules directory
      - name: cache dependencies
        uses: actions/cache@v3.2.4
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      # install the dependencies
      - name: install dependencies
        run: npm install  --force --legacy-peer-deps

      - name: Build project
        run: npm run build

      # # run the tests
      # - name: test
      #   run: npm test
